### ISSUE TITLE
[Bug]: open iOS notification while app is closed not passing the notification's payload to the app

### ISSUE THREAD

**Issue by avivdim** [Pushwoosh/pushwoosh-react-native-plugin#162]
### Documentation

- [X] I've checked the guide, but it doesn't help me to resolve the issue.

### Description

When I click on the iOS notification, it opens my app but the 'pushOpened' listener is not triggered. I added the NotificationService via Xcode and added some code to receive notifications with attachments:
![Screenshot 2024-03-28 at 11 41 57](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/assets/128924091/d863bcf7-1a05-4ebc-b21a-1273f72201a7)

It is also hard to test it as I'm not getting any push notification while in debug mode, so I need to release a new build every time and test it over and over again. If there is another solution for that, it would be nice.
Another issue is with this NotificationService.m when I'm trying to add the new code from your documentation, it says that 'PWNotificationExtensionManager.h' file is not found...
I'm currently using version 6.1.14 but also tested it with 6.1.30 and the issue still persists.
I'm using React Native version 0.68.2.
* Android is working fine even when the app is closed; the issue is only on iOS when the app is closed. When the app is in the background, everything is working, and I'm getting the payload using 'pushOpened' listener.

### Bug severity

High

### Steps to Reproduce

Send a push to the app, click on it while the app is closed.
The app is open but 'PushOpened' is not triggered, and I need to use notification payload to know where I should lead the user to.
issue is only on ios.

### Your Pushwoosh React Native Plugin version

6.1.14

### Affected platforms

- [ ] Android
- [X] iOS

### Affected OS versions and/or devices

tested on 16 and 17 ios

**Comment by enginseer-dev** [comment]
Hi @avivdim! The issue you're reporting was fixed with the [6.1.30](https://github.com/Pushwoosh/pushwoosh-react-native-plugin/releases/tag/6.1.30) release. Could you please test this version again? Please make sure that all dependencies are updated.
If the problem persists, please contact our support at help@pushwoosh.com for further investigation.

You're not receiving notifications in the Debug mode most likely because your Pushwoosh application is configured with the Production certificate. We recommend using separate apps for development and production.

> Another issue is with this NotificationService.m when I'm trying to add the new code from your documentation, it says that 'PWNotificationExtensionManager.h' file is not found...

Do I understand correctly that you're adding badges for your app using the code from this guide [Setting up Badges for React Native](https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/react-native/setting-up-badges-for-react-native)?

**Comment by avivdim** [comment]
Hi @enginseer-dev. Thanks for the detailed comment. I upgraded to version 6.1.30 again and it seems like the issue was that the iOS SDK wasn't updated and stayed on an old version. After updating the pod, it was working and the issue was solved as you said! Regarding the issue of not receiving push notifications in debug mode, I will try to check it again and will update if it is solved.

> Do I understand correctly that you're adding badges for your app using the code from this guide [Setting up Badges for React Native](https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/react-native/setting-up-badges-for-react-native)?

<img width="1304" alt="Screenshot 2024-03-30 at 15 20 20" src="https://github.com/Pushwoosh/pushwoosh-react-native-plugin/assets/128924091/26bac29b-cc14-43cd-8b34-290cc4b0be6e">

Actually, no. I was trying to use this link: https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/ios-push-notifications/ios-message-delivery-tracking.
I tried to follow the same steps and got the error "PWNotificationExtensionManager.h' file not found."
I will also check the badges guide, as it could be helpful for my app. However, it would be good to know why I am getting this error and need to revert to the old approach as shown in the bug image.

Thanks !

**Comment by enginseer-dev** [comment]
Hi @avivdim! It's great that the initial issue is resolved!

Regarding the Message Delivery Tracking, could you please try importing the class with `#import <Pushwoosh/PWNotificationExtensionManager.h>`? It should fix the error.

**Comment by avivdim** [comment]
Hi @enginseer-dev 

I don't receive any notifications on dev mode when running the real device and while connecting to Xcode, even when I'm trying to take hwid/token from a Pushwoosh sdk and sending notification via createMessage api its saying unknown device.any idea?

Regarding the second issue with message delivery tracking, the issue still showed even when I tried to import the class as you wrote.

**Comment by enginseer-dev** [comment]
@avivdim, since React Native does not automatically link all required dependencies to a target that was created manually, please make sure that the libs/frameworks are added to your project the way it's described in the [Setting up Badges for React Native](https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/react-native/setting-up-badges-for-react-native) article (4. Link dependencies to a target).

To troubleshoot the "unknown device" issue, could you please contact our support at help@pushwoosh.com? We will need to review your account and probably the device logs to determine the reason for the issue.
